{"uuid": "277cab1e-9dcc-4c2b-9e36-9c518edbc72a", "children": ["a8abd44b-f64b-41f3-8398-76b3166466d4"], "befores": [{"name": "driver", "status": "broken", "statusDetails": {"message": "selenium.common.exceptions.SessionNotCreatedException: Message: create container: Error response from daemon: No such image: selenoid/opera:88.0\n\n", "trace": "  File \"/opt/otus_project/lesson_project/env/lib/python3.10/site-packages/pluggy/_callers.py\", line 39, in _multicall\n    res = hook_impl.function(*args)\n  File \"/opt/otus_project/lesson_project/env/lib/python3.10/site-packages/_pytest/fixtures.py\", line 1122, in pytest_fixture_setup\n    result = call_fixture_func(fixturefunc, request, kwargs)\n  File \"/opt/otus_project/lesson_project/env/lib/python3.10/site-packages/_pytest/fixtures.py\", line 924, in call_fixture_func\n    fixture_result = fixturefunc(**kwargs)\n  File \"/opt/otus_project/lesson_project/conftest.py\", line 104, in driver\n    driver = webdriver.Remote(\n  File \"/opt/otus_project/lesson_project/env/lib/python3.10/site-packages/selenium/webdriver/remote/webdriver.py\", line 157, in __init__\n    self.start_session(capabilities, browser_profile)\n  File \"/opt/otus_project/lesson_project/env/lib/python3.10/site-packages/selenium/webdriver/remote/webdriver.py\", line 252, in start_session\n    response = self.execute(Command.NEW_SESSION, parameters)\n  File \"/opt/otus_project/lesson_project/env/lib/python3.10/site-packages/selenium/webdriver/remote/webdriver.py\", line 321, in execute\n    self.error_handler.check_response(response)\n  File \"/opt/otus_project/lesson_project/env/lib/python3.10/site-packages/selenium/webdriver/remote/errorhandler.py\", line 242, in check_response\n    raise exception_class(message, screen, stacktrace)\n"}, "start": 1661457977110, "stop": 1661457977115}], "start": 1661457977110, "stop": 1661457977181}