{"uuid": "d9cc9ce9-6a36-421c-9dc6-28729e6df45c", "children": ["c7b5ff2f-6a4a-4df9-8a5f-fd0fe856b711"], "befores": [{"name": "driver", "status": "broken", "statusDetails": {"message": "selenium.common.exceptions.SessionNotCreatedException: Message: create container: Error response from daemon: No such image: selenoid/opera:88.0\n\n", "trace": "  File \"/opt/otus_project/lesson_project/env/lib/python3.10/site-packages/pluggy/_callers.py\", line 39, in _multicall\n    res = hook_impl.function(*args)\n  File \"/opt/otus_project/lesson_project/env/lib/python3.10/site-packages/_pytest/fixtures.py\", line 1122, in pytest_fixture_setup\n    result = call_fixture_func(fixturefunc, request, kwargs)\n  File \"/opt/otus_project/lesson_project/env/lib/python3.10/site-packages/_pytest/fixtures.py\", line 924, in call_fixture_func\n    fixture_result = fixturefunc(**kwargs)\n  File \"/opt/otus_project/lesson_project/conftest.py\", line 104, in driver\n    driver = webdriver.Remote(\n  File \"/opt/otus_project/lesson_project/env/lib/python3.10/site-packages/selenium/webdriver/remote/webdriver.py\", line 157, in __init__\n    self.start_session(capabilities, browser_profile)\n  File \"/opt/otus_project/lesson_project/env/lib/python3.10/site-packages/selenium/webdriver/remote/webdriver.py\", line 252, in start_session\n    response = self.execute(Command.NEW_SESSION, parameters)\n  File \"/opt/otus_project/lesson_project/env/lib/python3.10/site-packages/selenium/webdriver/remote/webdriver.py\", line 321, in execute\n    self.error_handler.check_response(response)\n  File \"/opt/otus_project/lesson_project/env/lib/python3.10/site-packages/selenium/webdriver/remote/errorhandler.py\", line 242, in check_response\n    raise exception_class(message, screen, stacktrace)\n"}, "start": 1661457976905, "stop": 1661457976914}], "start": 1661457976905, "stop": 1661457976987}